name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - '28.2'
          - '29.4'
          - 'snapshot'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Emacs ${{ matrix.emacs_version }}
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: Set up Cask
        uses: cask/setup-cask@master

      - name: Install dependencies
        run: cask install

      - name: Run tests
        run: make test
